Acl/Controller/Component/AclFilterComponent.php

Check for admin prefix when redirecting to dashboard url

---

Acl/Config/Migration/1422516210_split_session.php
Acl/Config/events.php
Acl/Event/AclEventHandler.php
Install/Config/Data/SettingData.php

Enable separate session between frontend and admin.
Configurable in `Settings -> Access Control` section.

Add new config 'Access Control.splitSession'

---

Croogo/Console/Templates/croogo/actions/controller_actions.ctp
Croogo/Console/Templates/croogo/views/admin_index.ctp
Croogo/Console/Templates/croogo/views/admin_view.ctp
Croogo/Console/Templates/croogo/views/form.ctp
Croogo/View/Common/admin_index.ctp

Rebase of @ionas' PR: #628, #629, #630, #631, #633 
Please review and comment. CC: @croogo/contributors

2.2 bake templates improvements

---

FileManager/composer.json
FileManager/config/admin_menu.php
FileManager/src/Controller/Admin/AttachmentsController.php
FileManager/src/Controller/Admin/FileManagerController.php
FileManager/src/Controller/FileManagerAppController.php
FileManager/src/Model/Entity/Attachment.php
FileManager/src/Model/Table/AttachmentsTable.php
FileManager/src/Template/Admin/Attachments/add.ctp
FileManager/src/Template/Admin/Attachments/edit.ctp
FileManager/src/Template/Admin/Attachments/index.ctp
FileManager/src/Template/Admin/FileManager/browse.ctp
FileManager/src/Template/Admin/FileManager/create_directory.ctp
FileManager/src/Template/Admin/FileManager/create_file.ctp
FileManager/src/Template/Admin/FileManager/edit_file.ctp
FileManager/src/Template/Admin/FileManager/rename.ctp
FileManager/src/Template/Admin/FileManager/upload.ctp
FileManager/src/Utility/FileManager.php
FileManager/src/View/Helper/FileManagerHelper.php

3.0 filemanager updates - wip

---

Core/src/Model/Behavior/CopyableBehavior.php
Core/src/Model/Behavior/PublishableBehavior.php
Core/src/Model/Behavior/TrackableBehavior.php

Closes #669 
WIP: Please do not merge

3.0 behaviors - WIP

---

Blocks/src/Controller/Admin/BlocksController.php
Blocks/src/Event/BlocksEventHandler.php
Blocks/src/Template/Admin/Blocks/index.ctp
Blocks/webroot/js/admin.js
Core/src/Controller/CroogoAppController.php
Core/src/Model/Behavior/BulkProcessBehavior.php
Core/src/Template/Layout/admin.ctp
Core/src/View/Helper/JsHelper.php
Menus/src/Controller/Admin/LinksController.php
Menus/src/Model/Table/MenusTable.php
Menus/src/Template/Admin/Links/index.ctp
Menus/src/Template/Admin/Menus/index.ctp
Menus/webroot/js/admin.js
Nodes/src/Event/NodesEventHandler.php
Nodes/src/Model/Table/NodesTable.php
Nodes/src/Template/Admin/Nodes/index.ctp
Nodes/webroot/js/admin.js

Work in progress - do not merge

3.0 bulk - WIP

---

Blocks/src/Controller/Component/BlocksComponent.php
Blocks/tests/Fixture/BlockFixture.php
Core/src/Utility/StringConverter.php
Install/config/Data/BlockData.php
Nodes/src/Controller/NodesController.php
Nodes/tests/TestCase/View/Helper/NodesHelperTest.php

Caused error on /-URL when using "Recent Posts" block

Renamed Node to Nodes at some places (in tests, installer, comments)

---

Dashboards/src/Controller/Admin/AppController.php
Dashboards/src/Controller/Admin/DashboardsDashboardsController.php
Dashboards/src/Controller/AppController.php
Meta/src/Controller/Admin/AppController.php
Meta/src/Controller/AppController.php

While creating a new application on Croogo 3, after sync'ing the Aco's I received some errors regarding these issues.

Fixed Meta and Dashboards AppControllers

---

Acl/config/routes.php
Blocks/config/routes.php
Comments/config/routes.php
Contacts/config/routes.php
Core/config/routes.php
Dashboards/config/routes.php
Example/config/routes.php
Extensions/config/routes.php
FileManager/config/routes.php
Menus/config/routes.php
Nodes/config/routes.php
Settings/config/routes.php
Taxonomy/config/routes.php
Users/config/routes.php

Updated to the new way of defining routes in CakePHP 3.0.

Updated style of routes

---

Core/src/Shell/ExtShell.php
Core/src/View/Helper/CroogoHelper.php
Extensions/src/Controller/Admin/ExtensionsPluginsController.php
Extensions/src/CroogoPlugin.php
Extensions/src/Template/Admin/ExtensionsPlugins/index.ctp

`bin/cake ext list|activate|deactivate plugin <foo>` now works

Migrate ExtShell to 3.x

---

Acl/src/Controller/Component/FilterComponent.php

When a visitor came to a Croogo website, he was always redirected to the login page, because public authorization was always false due a new path. I've now used the Role alias to match it, now we're also not bind to any Aro id.

RFC: Fixed public authorization not working

---

Menus/src/Model/Table/LinksTable.php

New menus were not working since countercache has not been updated

Fixed counterCache for Menulinks

---

Taxonomy/src/Model/Table/VocabulariesTable.php

see https://github.com/ADmad/cakephp-sequence/commit/0b690d40ac343b395aabff6137c032a81ce5ca14

Changed behavior namespace on sequence behavior

---

Core/src/CroogoRouter.php
Install/config/Data/TypeData.php
Nodes/config/routes.php
Taxonomy/src/Model/Table/TypesTable.php

Bootstrap type routes automatically when `routes=true` is specified in params

Bootstrap type routes

---

Core/src/CroogoRouter.php
Install/config/Data/TypeData.php
Nodes/config/routes.php
Taxonomy/src/Model/Table/TypesTable.php

Reverts croogo/croogo#774
I merged it too soon :(

Revert "Bootstrap type routes"

---

Menus/src/View/Helper/MenusHelper.php

Fix string to boolean conversion

---

Install/src/Shell/InstallShell.php

the shell installer seems to have been broken while implementing the web installer.

Fixing Shell Installation

---

Taxonomy/src/Action/Admin/TermAddAction.php
Taxonomy/src/Action/Admin/TermEditAction.php
Taxonomy/src/Controller/Admin/TermsController.php
Taxonomy/src/Model/Behavior/TaxonomizableBehavior.php
Taxonomy/src/Model/Table/TermsTable.php
Taxonomy/src/Template/Admin/Terms/form.ctp
Taxonomy/src/Template/Admin/Terms/index.ctp

3.0 taxonomy updates

---

Dashboards/View/Helper/DashboardsHelper.php

[rus]
Из-за этого при определений в теме приложения, тот элемент не переопределялся
[eng]
Because of this, when defining the application theme, that element was not redefined

Fix PluginName for call element

---

Install/src/Controller/InstallController.php
Install/src/Template/Layout/install.ctp

Otherwise, Asset Generator.php was started

Correct path to croogo-admin in InstallController.php

---

Core/src/View/Helper/CroogoFormHelper.php

As mentioned in issue  #866 there was a typo in the CroogoFormHelper.

Fixed typo #866

---

Core/src/TestSuite/IntegrationTestCase.php
Nodes/tests/TestCase/Controller/NodesControllerTest.php

Remove references to Cake\Core\Plugin::routes().

Use PluginManager where needed.

---

Core/src/Plugin.php
Core/src/PluginManager.php
Core/src/Router.php

Allows for configuring the homepage in 4.0
And smoothly handles exceptions that occur during a migration from admin.

4.0 homepage

---

Core/src/Controller/Component/RecaptchaComponent.php
Core/src/View/Helper/RecaptchaHelper.php
FileManager/src/Model/Behavior/LinkedAssetsBehavior.php
Translate/src/Middleware/I18nMiddleware.php

Missed some small deprecations on the last round

Deprecations

---

Core/src/View/Helper/CroogoFormHelper.php
Core/src/View/Helper/CroogoHtmlHelper.php
Translate/src/Controller/Admin/TranslateController.php
Translate/src/Model/Behavior/TranslateBehavior.php
Translate/src/Template/Admin/Translate/index.ctp

Some small updates to helpers, and a fix for translations

4.0 updates

---

Core/src/Model/Behavior/PublishableBehavior.php
Nodes/src/Controller/Admin/NodesController.php
Nodes/src/Controller/Component/NodesComponent.php
Nodes/src/Controller/NodesController.php
Nodes/src/Template/Admin/Nodes/chooser.ctp
Nodes/src/Template/Admin/Nodes/index.ctp
Nodes/src/Template/Nodes/rss/index.ctp
Nodes/src/Template/Nodes/rss/promoted.ctp
Nodes/src/Template/Nodes/rss/term.ctp

Nodes: Use publish_start field instead of created

---

Core/src/Template/Element/masthead.ctp
Core/webroot/css/custom.css
FileManager/src/Controller/Admin/AttachmentsController.php
FileManager/src/Event/FileManagerEventHandler.php
FileManager/src/Model/Behavior/LinkedAssetsBehavior.php
FileManager/src/Model/Table/AttachmentsTable.php
FileManager/src/Template/Admin/Attachments/browse.ctp
FileManager/src/Template/Admin/Attachments/index.ctp
FileManager/src/Template/Element/admin/asset_list.ctp
FileManager/src/Utility/FileManager.php
Meta/src/View/Helper/MetaHelper.php
composer.json

For poster generation, requires `ffmpeg` binary and composer package:`char0n/ffmpeg-php`
The aforemention packages are optional. If they are not present, the poster generation is a no-op.

4.0 - improve video handling

---

Core/src/Template/Bake/Plugin/config/routes.php.twig
Core/src/Template/Bake/Plugin/src/Controller/Admin/AppController.php.twig
Core/src/Template/Bake/Plugin/src/Controller/AppController.php.twig

Corrected AppController inheritance and removed resulting excess code.

Bake theme tweaks
