croogo/croogo

Extensions/Controller/ExtensionsLocalesController.php
Extensions/View/ExtensionsLocales/admin_index.ctp

Much friendlier than changing to the Settings page and manually clearing
the Site.locale value.

Add button to reset current locale

---

Croogo/webroot/js/typeahead_autocomplete.js

Typeahead was basically broken in 26d043d11fe6bab5c32a71d0ccccf4f87a3059b3 and was overwriting the hidden field all the time. This fix retains the original commit's goals.

Fixed typeahead overzealously resetting hidden field

---

Acl/Controller/AclActionsController.php
Croogo/Test/Case/AllCroogoTestsTest.php

Without `escape = false`, the `<warning>` gets escaped and visible in the flash message.

Fix: Escape flash message in acl_actions/admin_generate

---

Acl/src/Controller/Component/FilterComponent.php
Core/src/Controller/CroogoAppController.php

Currently no table is used for the Cake's Auth Component (e.g. `$this->Auth->identify();`). Now I default this to Croogo's Users table.

Use Croogo's Users table for authentication

---

Comments/Model/Comment.php
Contacts/Model/Contact.php
Contacts/Model/Message.php
Nodes/Model/Node.php
Users/Model/Role.php
Users/Model/User.php

This fixes many deprecated messages when using the latest version of Cake2.

Updated notEmpty to notBlank validation rule

---

Croogo/Controller/CroogoAppController.php

This is due to cakephp/cakephp@5e60cc5d182e6131e3fbdfdf69f49d560c9ff78b
The broken functionality is in `/admin/file_manager/attachments/add`

Fix: broken view path searching

---

Core/src/Link.php
Core/src/Utility/StringConverter.php
Menus/src/View/Helper/MenusHelper.php

This is a partial revert of ff8bf4ddc5f2c3c08a8dc6f714a1351d242a380a
Using `/` in this case feels more natural.  So instead of changing our separator to `|`, values containing the `/` character must be urlencoded instead. Eg: `plugin:Croogo%2FNodes/controller:Nodes/action:promoted`.

Change link separator back to / since values should be urlencoded

---

Menus/src/View/Helper/MenusHelper.php

Menus:
Now it is possible to change the sub-tag (li-tag) according to the main tag via new option "subTag" analog to "tag" and customize it via "subTagAttributes" option, according to main-tag's "tagAttributes". Enabled styling of custom menus.

added possibility to change sub-tag in menus and add class on it

---

Croogo/Model/Behavior/OrderedBehavior.php

Specify $Model->alias . '.' . $this->settings[$Model->alias]['field'] in updateAll() calls to fix issues arising from non unique fieldnames in belongsTo associations [Model::updateAll() force joins belongsTo associations]

Bug fix OrderedBehavior.php

---

Blocks/src/Controller/Admin/BlocksController.php
Comments/src/Controller/Admin/CommentsController.php
Comments/src/Controller/CommentsController.php
Contacts/src/Controller/Admin/MessagesController.php
Core/src/Controller/AppController.php
Core/src/Controller/ErrorController.php
Core/src/Controller/HookableComponentInterface.php
Core/src/Controller/HookableComponentTrait.php
Extensions/src/Event/HookableComponentEventHandler.php

I'm open if anyone has better ideas.

Avoid registering non-action public methods to acl

---

Menus/Controller/LinksController.php

Looks like d5a61ca removed this line inadvertently while making some other changes. Without setting the tree scope before performing the save, a parent change can cause "out of scope" changes as well.
Specifically, lets say we have two menus, one with 2 links, another with 3;
```
Link
id=1, menu_id=1, lft=1, rght=4
id=2, menu_id=1, lft=2, rght=3
id=3, menu_id=2, lft=1, rght=6
id=4, menu_id=2, lft=2, rght=3
id=5, menu_id=2, lft=4, rght=5
(structure)
link1 (in menu 1)
link2
link3 (in menu 2)
link4
link5
```
Notice that both of these menus have the same general structure, and hence some of the links have the same lft/rght values. That's normal. Next, lets try to re-parent link2 using the standard edit form and the dropdown box, for example, we want to make link2 a sibling of link1 rather …

setTreeScope before edit save

---

Core/config/croogo_bootstrap.php

By default, applications do not have a prefix set, and engines will inject their own. We default to `cake_`, as is specified in most engines.
This probably will fix two undefined index errors during test runs.

Use the Hash class to get the prefix

---

Extensions/src/Template/Admin/Plugins/add.ctp

Resolves the issue #816. New zipped extensions are now uploaded and can be enabled/disabled from admin panel.

Fixes #816 where uploading of zipped plugins fail

---

Core/src/Plugin.php

Fixed the path in Croogo's `Plugin::delete()` method. Files are now properly deleted.

Fixed pluginPath in plugin delete method. Fixes #819

---

Croogo/View/Helper/CroogoHelper.php

CroogoStatus::statuses() can return different status groups, so allow CroogoHelper::statuses to request specific statusType.

Expose $statusType for statuses()

---

Nodes/Controller/NodesController.php

Makes sense that if you can set default paginate->limit value from params (using nodes_per_page) you should also be able to set the default paginate->order value.  May want to change the name of the params variable used to sort_order or something more specific to its use case.

Add ability to set paginate->order from params

---

Users/Controller/UsersController.php

According to https://book.cakephp.org/2.0/en/core-libraries/components/authentication.html $this->redirect($this->Auth->redirectUrl()) should be used instead of $this->redirect($this->Auth->redirect()).
Changing this would require CakePHP version 2.3+ ... but would this be a problem?

Replace Auth::redirect() with Auth::redirectUrl()

---

Croogo/View/Helper/ImageHelper.php

Hi,
When we add a pictures using resize function ( $this->Image->resize() ), we see that there is no space between image path in src and the first attribute ex:
Also that cause HTML validation errors : No space between attributes
The solution is add space in parameter :
$this->Html->_parseAttributes($htmlAttributes, null, ' ', ' ')

Add space before and after attributes in img

---

Nodes/Controller/NodesController.php

Similar to PR #790 found in the LinksController, the NodesController is also affected by improper scoping with its use of the TreeBehavior. Links are "scoped" within their containing Menu. Nodes should be "scoped" within their Type.

Node Reordering with Tree Behavior

---

Nodes/src/Template/Nodes/index.ctp
Nodes/src/Template/Nodes/promoted.ctp
Nodes/src/Template/Nodes/search.ctp
Nodes/src/Template/Nodes/term.ctp

Without these modifications, paginations links cannot be rendered, as routes cannot be inferred without `type` param

Fix links for Nodes not called `blog`

---

Nodes/src/Template/Element/node_info.ctp
Nodes/src/Template/Element/node_more_info.ctp
Nodes/src/View/Helper/NodesHelper.php

Fix node elements. Replace cakephp 2 code by cakephp 3 because "node_info" and "node_more_info" are already not displayed.

fix node elements (cakephp 2 legacy)

---

Translate/config/routes.php

Redirect routes cause the request parameter to be null, this
causes an internal server error as the URL filter in the translate
plugin tries to get a parameter from the request.
This change makes the request parameter optional.

Make URL filter work on redirect routes

---

.gitignore

I guess most have global ignore for these, but I don't. Is this OK?

Ignore composer.lock and the vendor/ directory

---

tests/test_app/config/bootstrap.php
tests/test_app/src/Application.php

Placing Application.php in tests/test_app/ defaults tests to use
middleware automagically. I copied Application.php from
cakephp/app@3.8.0 This addresses the deprecation message:
"Dispatcher is deprecated. You should update your application
to use the Http\Server implementation instead. -
vendor/cakephp/cakephp/src/TestSuite/LegacyRequestDispatcher.php,
line: 72"
The above message occurred for every controller/integration test (around 40 times).
tests/test_app/config/bootstrap.php is referenced in Application.php
though it doesn't do anything.
References for more info:
https://book.cakephp.org/3.0/en/development/application.html#adding-http-stack
https://github.com/cakephp/app/blob/3.8.0/src/Application.php
https://book.cakephp.org/3.0/en/appendices/3-6-migration-guide.html#deprecations …

Use middleware by default in tests.

---

phpcs.xml.dist

Should allow most IDE to choose correct sniffs.

phpcs.xml.dist Default to CakePHP Core sniffs

---

Core/src/Model/Table/CroogoTable.php

Resolves #922 
I see the UsersTable was already fixed between 3.0 and 4.0, so my search through the library found only one more file with offending regex's. As stated in the issue, this does not affect php 7.2 environments or earlier, only those 7.3 and later.

fix regex for pcre2

---

Core/src/PluginManager.php

During CLI installation, the missing database would prevent settings from being loaded properly, causing the installation process to stop. Catching the PdoException and ignoring it during installation allows the process to continue.

Install: Catch all exceptions including missing database

---

Core/config/bootstrap.php

When baking some plugin models after using phinx for migrations, one of the models had a bogus association to phinxlog.
For example, I'm baking a Books plugin, with a Books model and an Authors model. After migrating an initial setup of the tables, the database contains a `books_phinxlog` table to record the migrations completed. Then, when baking the Books model, bake thinks that log table is a join table and associates them with a belongsToMany. This is not what's intended, but rather an unfortunate naming standard by Phinx with respect to Cake naming standards.
So, it's only when the model name and the plugin name are the same that this should occur, but there might be some other cases that I can't foresee. In any case, it would be extremely rare that someone actually wants a phinxlog …

Remove fake baked phinx associations

---

Core/src/Template/Element/masthead.ctp
Meta/src/View/Helper/MetaHelper.php
Nodes/config/bootstrap.php
Nodes/src/Template/Admin/Nodes/form.ctp

Closes #969.
The main change is that Nodes.Excerpt will now be a marked up field instead of text only. Custom production code assuming excerpt is text may now need to strip_tags. Existing Core code using excerpt has been updated as part of this PR.

Marked up excerpt
